Forum/Models/ErrorViewModel.cs
namespace Forum.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Forum/Models/MessageListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Forum.BaseLogic.DataHandler;
using Forum.Repository.DataBase;
using Forum.Repository.DataBase.Models;
using PagedList.Core;
using AutoMapper;
namespace Forum.Web.Models
{
    public class MessageListViewModel
    {
        public PaginatedMessageList<MessageViewModel> PaginatedMessageList { get; set; }

        public IQueryable<MessageViewModel> GetMesageList()
        {
            return PaginatedMessageList.MessageList;
        }

        public int GetPageNumber()
        {
            return PaginatedMessageList.PageNumber;
        }

        public bool GetHasNextPage()
        {
            return PaginatedMessageList.HasNextPage;
        }

        public bool GetHasPrevPage()
        {
            return PaginatedMessageList.HasPreviousPage;
        }

        public MessageListViewModel(PaginatedMessageList<MessageModel> paginatedMessageList)
        { 
            var messageList = new List<MessageViewModel>();
            foreach (var message in paginatedMessageList.MessageList)
            {
                messageList.Add(Mapper.Map<MessageViewModel>(message));
            }
            PaginatedMessageList =new PaginatedMessageList<MessageViewModel>(paginatedMessageList.PageNumber,paginatedMessageList.PageSize,paginatedMessageList.TotalPages, messageList.AsQueryable());
        }
    }
}

Forum/Models/MessageViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Forum.Repository.DataBase.Models;

namespace Forum.Web.Models
{
    public class MessageViewModel
    {
        
        public int Id { get; set; }
    
        [Required]
        [RegularExpression("[a-zA-Z0-9]{0,}", ErrorMessage = "Wrong name, only Latin error")]
        [StringLength(maximumLength:50)]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "mm/dd/yyyy")]
        public DateTime Date { get; set; }

        [Required]
        [StringLength(maximumLength:50)]
        public string MessageTopic { get; set; }

        [Required]
        [StringLength(maximumLength:50)]
        public string MessageСategory { get; set; }

        [Required]
        [StringLength(maximumLength: 256)]
        public string MessageText { get; set; }
    }
}

Forum/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using Forum.BaseLogic.DataHandler.Enums;
using Forum.BaseLogic.DataHandler.Services;
using Forum.Web.Models;
using Forum.Repository.DataBase.Models;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Queue;
using Newtonsoft.Json;

namespace Forum.Web.Controllers
{
    public class ForumController: Controller
    {
      
        private readonly IDataHandlerService _dataHandlerService;


        public ForumController(IDataHandlerService dataHandlerService)
        {
            _dataHandlerService = dataHandlerService;  
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AllMessages(int? page, SortParam sortParam)
        {
            ViewData["NameSort"] = sortParam == SortParam.UserNameAsc ? SortParam.UserNameDesc : SortParam.UserNameAsc;
            ViewData["DateSort"] = sortParam == SortParam.DateAsc ? SortParam.DateDesc : SortParam.DateAsc;
            ViewData["CurrentSort"] = sortParam;

            var pageNumber = page ?? 1;

            return pageNumber < 0 
                ? PartialView("WrongPageNumber") 
                : PartialView ( new MessageListViewModel(_dataHandlerService.GetPaganedMessageList(pageNumber, sortParam)));
        }

        [HttpGet]
        public IActionResult Message(int? messageId)
        {

            ViewData["Message"] = "Write your message";
            ViewBag.MessageAction = MessageAction.Add;
            return PartialView();
        }

        [HttpGet]
        public IActionResult UpdateMessage(int id)
        {
            var messageView = Mapper.Map<MessageViewModel>(_dataHandlerService.GetDataHandler().GetMessageById(id));
            ViewBag.MessageAction = MessageAction.Update;
            return PartialView("Message", messageView);
        }

        [HttpPost]
        public IActionResult DeleteMessage(int id, int page, SortParam sortParam)
        {
            return PartialView("AllMessages",new MessageListViewModel(_dataHandlerService.DeleteMessageAndGetNewList(id,page,sortParam)));
        }

        [HttpPost]
        public IActionResult Message(MessageViewModel messageView, MessageAction messageAction)
        {
            if (!ModelState.IsValid) return PartialView(messageView);
            var messageModel = Mapper.Map<MessageModel>(messageView);
            _dataHandlerService.AddOrUpdateMessage(messageModel,messageAction);
            return PartialView("success");
        }

       
    }
}

Forum/Views/Forum/AllMessages.cshtml
@model Forum.Web.Models.MessageListViewModel
@using PagedList.Core.Mvc;

@{
    ViewData["Title"] = "Home Page";
}
<div class="col-lg-8">
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        <a asp-action="AllMessages" asp-route-sortParam="@ViewBag.NameSort"
                           data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
                            User Name
                        </a>
                    </th>
                    <th>
                        <a asp-action="AllMessages" asp-route-sortParam="@ViewBag.DateSort"
                           data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
                            Date
                        </a>

                    </th>

                    <th>Topic</th>
                    <th>Category</th>
                    <th>Message</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var message in Model.PaginatedMessageList.GetPaginatedMessageList())
                {
                    <tr>
                        <td>@message.UserName</td>
                        <td>@message.Date</td>
                        <td>@message.MessageTopic</td>
                        <td>@message.MessageСategory</td>
                        <td><textarea>@message.MessageText</textarea></td>
                        <td>
                            <a class="btn btn-danger" asp-action="DeleteMessage" asp-route-id="@message.Id" asp-route-page="@Model.GetPageNumber()" asp-route-sortParam="@ViewData["CurrentSort"]" data-ajax="true" data-ajax-method="post" data-ajax-update="#update">Delete</a>
                        </td>
                        <td>
                            <a class="btn btn-default" asp-action="UpdateMessage" asp-route-id="@message.Id" data-ajax="true" data-ajax-method="get" data-ajax-update="#update">Update</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <br />

        @{
            var prevDisabled = !Model.PaginatedMessageList.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.PaginatedMessageList.HasNextPage ? "disabled" : "";
        }

        <a asp-action="AllMessages"
           asp-route-sortParam="@ViewData["CurrentSort"]"
           asp-route-page="@(Model.PaginatedMessageList.PageNumber - 1)"
           class="btn btn-default @prevDisabled"
           method="get"
           data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
            Previous
        </a>

        <a asp-action="AllMessages"
           asp-route-sortParam="@ViewData["CurrentSort"]"
           asp-route-page="@(Model.PaginatedMessageList.PageNumber + 1)"
           class="btn btn-default @nextDisabled"
           method="get"
           data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
            Next
        </a>

    </div>
</div>

Forum/Views/Forum/Index.cshtml
@{
    ViewData["Title"] = "Index";
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

        <div id="update" class="container">
            @Html.Partial("Welcom")
        </div>

Forum/Views/Forum/Message.cshtml
@using Forum.Web.Models
@model Forum.Web.Models.MessageViewModel
@{
    ViewData["Title"] = "Message";
}

<h2>@ViewData["Message"]</h2>

<form asp-antiforgery="true"  asp-action="Message" asp-route-messageAction="@ViewBag.MessageAction" data-ajax="true" data-ajax-method="post" data-ajax-update="#update">
   
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @if (Model != null)
    {
        <div class="form-group">
            <input asp-for="@Model.Id" type="hidden" class="form-control"/>
            <span asp-validation-for="@Model.Id" class="text-danger"></span>
        </div>
    }
        <div class="form-group">
            <label asp-for="@Model.UserName" ></label>
            <input asp-for="@Model.UserName" class="form-control"/>
            <span asp-validation-for="@Model.UserName"  class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Date">Date</label>
            <input asp-for="@Model.Date" class="form-control" type="text"/>
            <span asp-validation-for="@Model.Date" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.MessageTopic">MessageTopic</label>
            <input class="form-control" asp-for="@Model.MessageTopic"/>
            <span asp-validation-for="@Model.MessageTopic" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.MessageСategory">MessageСategory</label>
            <input class="form-control" asp-for="@Model.MessageСategory"/>
            <span asp-validation-for="@Model.MessageСategory" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="@Model.MessageText">Text Area</label>
            <textarea class="form-control" rows="10" asp-for="@Model.MessageText"></textarea>
            <span asp-validation-for="@Model.MessageText" class="text-danger"></span>
        </div>
      
    <button type="submit">Clik Me to send Message</button>
</form>

Forum/Views/Forum/Welcom.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<h1>Welcom to our Forum</h1>
<div  class="loader">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
</div>
  

Forum/Views/Forum/WrongPageNumber.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<h1>WrongPageNumber</h1>

Forum/Views/Forum/success.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<script src="js/site.min.js"></script>
<div>
    <h1>Message delivered</h1>
    
</div>

Forum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Forum</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    
    <style>
         *{box-sizing:border-box}
    body {
    margin: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    }
    @@keyframes loader {
    0% {transform:rotate(-45deg)}
    50%{transform:rotate(-135deg)}
    100%{transform:rotate(-225deg)}}
    @@keyframes span-1 {
    0% {transform:translate(0);}
    50%{transform:translate(-50px, 0);border-color:#EE4D68}
    100%{transform:translate(0);}}
    @@keyframes span-2 {
    0%{transform:translate(0);}
    50%{transform:translate(50px, 0);border-color:#875678}
    100%{transform:translate(0);}}
    @@keyframes span-3 {
    0%{transform:translate(0);}
    50%{transform:translate(0, -50px);border-color:#FF9900}
    100%{transform:translate(0);}}
    @@keyframes span-4 {
    0%{transform:translate(0);}
    50%{transform:translate(0, 50px);border-color:#00E4F6}
    100%{transform:translate(0);}}
    .loader {
    width: 50px;
    height: 50px;
    position: relative;
    animation: loader 2s infinite ease-in-out;
    }
    .loader span {
    width: 50px;
    height: 50px;
    position: absolute;
    left: 0;
    top: 0;
    border: 4px solid #0B1B48;
    }
    .loader span:nth-child(1) {
    animation: span-1 2s ease-in-out infinite;
    }
    .loader span:nth-child(2) {
    animation: span-2 2s ease-in-out infinite;
    }
    .loader span:nth-child(3) {
    animation: span-3 2s ease-in-out infinite;
    }
    .loader span:nth-child(4) {
    animation: span-4 2s ease-in-out infinite;
    }

    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                      <a asp-controller="Forum" asp-action="AllMessages"   data-ajax="true" data-ajax-method="get" data-ajax-update="#update">
                        AllMessages
                    </a>
                    </li>
                    <li>
                        <a  asp-controller="Forum" asp-action="Message"  data-ajax="true" data-ajax-mode="replace" method="get"
                            data-ajax-update="#update">
                            CreateMessage
                        </a>
                    </li>
                  
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        
        <hr />
        <footer>
            <p>&copy; 2018 - Forum</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    </environment>
        <environment exclude="Development">
        <script src="~/js/site.js" asp-append-version="true"></script>

        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>


    @RenderSection("Scripts", required: false)
</body>
</html>